---
engines:
  spotbugs:
    exclude_paths:
      - "settings.xml"
exclude_paths:
  - "**/static/**"
  - "**/*.js"
  - "**/*.css"
  - "**/*.html"
  - "**/*.zip"
  - "**/*.tgz"
  - "**/*.sh"
  - "**/*.bat"
  - "**/*.md"
  - "settings.xml"
